# Generated by Django 6.0.5 on 2026-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
